M48
; DRILL file {KiCad 9.0.1-1.fc42} date 2025-04-24T00:42:52-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-24T00:42:52-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1-1.fc42
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.700
%
G90
G05
T1
X153.9Y-68.135
X153.9Y-72.985
T2
X156.93Y-67.835
X156.93Y-73.285
T3
X103.5Y-47.5
X103.5Y-96.5
X161.5Y-47.5
X161.5Y-96.5
M30
